### ISSUE TITLE
Here are some taobao search terms I collected

### ISSUE THREAD

**Issue by TomKeddie** [lab0x0/makerdic#1]
https://www.evernote.com/shard/s45/sh/3254c335-4b40-42ee-a521-c414e4690d9d/0e1f7a9aa8a62dd4e2fb05b10671054e

**Comment by janekm** [comment]
Thanks, there's some great stuff in there. I put the first section under the taobao cheatsheet for now, the second half looks like it has a lot of overlap with the mechanical terms already in the pdf so I'll have to find someone to merge them properly (I'm hoping to find a few students to help out with that and generally fleshing out useful terms).

**Comment by TomKeddie** [comment]
Thanks, I think you're right about the second section. Am away right now without a computer, next time I will send a pull request.
